server:
  port: '8084'

spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/college?useSSL=false
    password: '123456'
  jpa:
    properties:
      hibernate:
        dilect: org.hibernate.dilect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: 'true'
welcome:
  message: Welcome to spring boot API

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: qa
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/qa_spring?useSSL=false
    password: '123456'
  jpa:
    properties:
      hibernate:
        dilect: org.hibernate.dilect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: 'true'
welcome:
  message: Welcome to spring boot API

---

spring:
  profiles: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/prod_spring?useSSL=false
    password: '123456'
  jpa:
    properties:
      hibernate:
        dilect: org.hibernate.dilect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: 'true'
welcome:
  message: Welcome to spring boot API